# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check windows info

on:
  push:

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
    # check out this project
    - uses: actions/checkout@v3
      with:
        path: testteeny

    # checkout project we are playing with
    - uses: actions/checkout@v3
      with:
        repository: webstech/semantic-release
        path: semantic-release
        ref: t1

    # set git globals
    - run: git config --global user.name github-actions
    - run: git config --global user.email github-actions@github.com

    - name: Check git
      if: ${{ 1 == 0 }}
      shell: cmd
      working-directory: semantic-release
      run: |
        git config -l --global
        git config -l --local

    - name: Update files
      if: ${{ 1 == 0 }}
      shell: cmd
      working-directory: semantic-release
      run: |
        rem copy /Y ..\testteeny\plugin-configuration-test.js safe\*

    - run: npm ci
      working-directory: semantic-release
    - run: npm upgrade
      working-directory: semantic-release

    - run: npm run test:dev
      working-directory: semantic-release

    - name: Check files
      if: ${{ 1 == 0 }}
      shell: cmd
      working-directory: semantic-release
      run: |
        dir bin
        dir safe
        rem dir /s
        where bash
        node -p process.platform
        rem node -p "{const which = require('which');which.sync('bash')}"
        rem node ..\testteeny\eggselent.js

    - run: npm test
      if: ${{ 1 == 0 }}
      working-directory: semantic-release
