# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check windows info

on:
  push:

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        path: testteeny

    - uses: actions/checkout@v3
      with:
        repository: webstech/testdouble.js
        path: testdouble
        ref: cw/winwin

    - name: Check git
      shell: cmd
      working-directory: testdouble
      run: |
        git config -l --global
        git config -l --local

    - name: Update files
      shell: cmd
      working-directory: testdouble
      if: ${{ 1 == 0 }}
      run: |
        rem copy /Y ..\testteeny\plugin-configuration-test.js safe\*

    - run: npm ci
      working-directory: testdouble

    - name: Check files
      shell: cmd
      working-directory: testdouble
      if: ${{ 1 == 0 }}
      run: |
        dir bin
        dir safe
        rem dir /s
        where bash
        node -p process.platform
        rem node -p "{const which = require('which');which.sync('bash')}"
        rem node ..\testteeny\eggselent.js

    - run: npm test
      working-directory: testdouble
